name: Margarita Coyle
favicon: null
layout_spectrum: 0.44655572436749935
typography_spectrum: 0.9376347223296762
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.2925961387809366
  lightness: 0.7088144393637776
  saturation: 0.00717472517862916
  rhythmicContrast: 0.24484870536252856
purpose: []
